### ISSUE TITLE
package ‘affy2sv’ is not available

### ISSUE THREAD

**Issue by esh81** [isglobal-brge/affy2sv#1]
Hi, 

I'm trying to install affy2sv on R and am getting this error: 

`Warning message:
package ‘affy2sv’ is not available (for R version 3.5.1) 
`

I am using 
`install.packages("affy2sv")` to try to install affy2sv.

Has the R dependency changed for the package? I also tried R 4.0 and I got the same error. 

Thank you!

**Comment by carleshf** [comment]
Hi @esh81!

As my see, `affy2sv` is not a released package at Biocondcutor nor at CRAN. Therefore the `install.packages` will not find it.

To install the package, you have to clone it and install it manually.
